guests = ["Albert Einstein", "Nikola Tesla", "Robert Oppenheimer", "Alan Turing"]
print("I've found a bigger table!")
guests.insert(0, "Alexander the Great")
guests.insert(2, "Winston Churchill")
guests.append("Gengis Khan")
print(f"Hello {guests[0]}, I would like to invite you to the dinner")
print(f"Hello {guests[1]}, I would like to invite you to the dinner")
print(f"Hello {guests[2]}, I would like to invite you to the dinner")
print(f"Hello {guests[3]}, I would like to invite you to the dinner")
print(f"Hello {guests[4]}, I would like to invite you to the dinner")
print(f"Hello {guests[5]}, I would like to invite you to the dinner")
